#!/usr/bin/env bash

set -e

rm -rf build

cmake -GNinja -DGGML_NATIVE:BOOL=TRUE -DGGML_LTO:BOOL=TRUE -DLLAMA_BUILD_EXAMPLES:BOOL=FALSE -DLLAMA_BUILD_SERVER:BOOL=TRUE -DLLAMA_BUILD_TESTS:BOOL=FALSE -DLLAMA_CURL:BOOL=TRUE -DBUILD_SHARED_LIBS:BOOL=TRUE -DGGML_METAL:BOOL=TRUE -DLLAMA_BUILD_NUMBER=0 -DLLAMA_BUILD_COMMIT:STRING=dev -DGGML_METAL_EMBED_LIBRARY:BOOL=TRUE -DCMAKE_C_FLAGS="-O3 -mcpu=native -pipe" -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld -B build -S .

cmake --build build
